In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [9]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [10]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones((2,8),int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(3,2)

array([[0.96335212, 0.14101123],
       [0.32016307, 0.69846402],
       [0.74804487, 0.85015503]])

In [23]:
np.random.rand(3,2)

array([[0.83772615, 0.21810067],
       [0.78435045, 0.60067571],
       [0.95356037, 0.65355014]])

In [24]:
np.random.randn(3,2)

array([[ 0.31583607, -0.50117855],
       [-0.33019531, -0.43156619],
       [ 0.17461142,  0.44476377]])

In [25]:
np.random.randint(34,100)

86

In [26]:
np.random.randint(20,56,100)

array([55, 46, 43, 52, 34, 31, 40, 38, 51, 20, 50, 27, 41, 40, 31, 29, 32,
       22, 27, 45, 52, 41, 43, 41, 55, 45, 20, 48, 29, 39, 25, 54, 45, 33,
       50, 23, 26, 51, 37, 29, 54, 29, 37, 48, 23, 55, 48, 52, 27, 26, 44,
       24, 54, 21, 25, 29, 31, 22, 24, 23, 44, 48, 44, 22, 23, 52, 34, 54,
       20, 23, 29, 36, 50, 44, 34, 50, 29, 34, 47, 47, 36, 30, 38, 21, 30,
       33, 37, 55, 45, 55, 51, 53, 27, 33, 35, 27, 27, 27, 54, 51])

In [27]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
rand_array=np.random.randint(0,100,20)
rand_array

array([87, 38, 85,  1, 48, 36, 16, 58, 38, 45, 16, 58, 88, 10, 13, 17, 18,
        0, 64, 54])

In [30]:
sample_array.reshape(2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
rand_array.min()

0

In [32]:
rand_array.argmin()

17

In [33]:
rand_array.max()

88

In [36]:
sample_array[-3]

27

In [37]:
sample_array[3:7]

array([3, 4, 5, 6])

In [38]:
sample_array[1:4]=100
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [40]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
###TWO DIMENSIONAL ARRAY

In [44]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [45]:
sample_matrix[0][2]

1

In [46]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [47]:
sample_matrix[2]

array([56, 76, 24,  7])

In [49]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [ ]:
###SELECTION TECHNIQUES

In [51]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [52]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [53]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [54]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [55]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [56]:
np.max(sample_array)

19

In [57]:
np.min(sample_array)

1

In [58]:
np.argmax(sample_array)

18

In [59]:
np.argmin(sample_array)

0

In [60]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [61]:
np.std(sample_array)

5.477225575051661

In [62]:
np.var(sample_array)

30.0

In [63]:
np.mean(sample_array)

10.0

In [65]:
array=np.random.randn(3,4)
array

array([[ 1.76576283, -0.69591734,  0.36134428, -0.80899103],
       [ 0.26358148,  2.35102679, -0.60608304,  0.40293165],
       [ 0.15985156,  1.36837933,  0.49168621,  2.21045413]])

In [66]:
np.round(array,decimals=4)

array([[ 1.7658, -0.6959,  0.3613, -0.809 ],
       [ 0.2636,  2.351 , -0.6061,  0.4029],
       [ 0.1599,  1.3684,  0.4917,  2.2105]])

In [67]:
sports=np.array(["golf","cricket","fball","cricket","football"])
np.unique(sports)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')